name: Add Label on Push
on:
  push:
    branches:
      - main  # Replace with your desired branch

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Add label
        uses: actions/github-script@v4
        with:
          script: |
            const payload = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['hello']  # Change the label name to 'hello'
            };

            await github.issues.addLabels(payload);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
