name: Add Label on Push
on:
  push:
    branches:
      - main  # Replace with your desired branch

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add label
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels
          headers: |
            {
              "Authorization": "token ${{ secrets.GITHUB_TOKEN }}",
              "Content-Type": "application/json"
            }
          body: |
            {
              "labels": ["hello"]
            }
